server:
  port: 8080

spring:
  application:
    name: simple-rest
  datasource:
    url: jdbc:postgresql://localhost:5432/simple
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  mandatory-file-encoding: utf-8

#SWAGGER
swagger:
  contact:
    name: Unknown person
    email: user@email.com
  application:
    version: @project.version@
    description: @project.description@
springdoc:
  api-docs:
    path: /swagger/api-docs
  swagger-ui:
    path: /swagger/ui