server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/simple
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#SWAGGER
swagger:
  contact:
    name: Unknown person
    email: user@email.com
  application:
    version: @project.version@
    description: @project.description@
springdoc:
  api-docs:
    path: /swagger/api-docs
  swagger-ui:
    path: /swagger/ui